### ISSUE TITLE
Update to v1.7

### ISSUE THREAD

**Issue by myfairsyer** [mjarosie/jq-chocolatey-package#2]
Please update to v1.7. Thanks!

**Comment by myfairsyer** [comment]
I was about to submit a PR myself (looked up URLs, sha512s, the unchanged copyright notice in jq's COPYING file), but now just saw https://github.com/jqlang/jq/issues/2886

Thus I won't continue, assuming that you already are taking care of the update.

Thanks again!

**Comment by mjarosie** [comment]
Just submitted the package for review: https://community.chocolatey.org/packages/jq#versionhistory. I subscribe to `jq` releases so I was notified about the new version being released, I was planning to update the choco version but didn't find enough time during the week. Thanks for reminding though! : ) I'll close the issue once the package gets accepted.

**Comment by myfairsyer** [comment]
Status is _approved_ and there have already been ~800 downloads:
![image](https://github.com/mjarosie/jq-chocolatey-package/assets/13559472/58b2f594-df50-49d3-92b0-e57b53863d85)

**Comment by mjarosie** [comment]
Yes they've approved it tonight. Thanks.

**Comment by myfairsyer** [comment]
Thank _you_!
